tool_map = {
    "1.1": ("Để Chạy Tool Golike Instagram", "obf-golike_instagram.py"),
    "1.2": ("Để Chạy Tool Golike Threads", "obf-golike_threads.py"),
    "2.1": ("Để Chạy Tool TDS Facebook", "obf-tds_facebook.py"),
    "2.2": ("Để Chạy Tool TDS Pro5", "obf-tds_pro5.py"),
    "2.3": ("Để Chạy Tool TDS Instagram", "obf-tds_instagram.py"),
    "2.4": ("Để Chạy Tool TDS TikTok", "obf-tds_tiktok.py"),
    "3.1": ("Để Chạy Tool TTC Facebook", "obf-ttc_facebook.py"),
    "3.2": ("Để Chạy Tool TTC Pro5", "obf-ttc_pro5.py"),
    "3.3": ("Để Chạy Tool TTC Instagram", "obf-ttc_instagram.py"),
    "3.4": ("Để Chạy Tool TTC TikTok", "obf-ttc_tiktok.py"),
    "4.1": ("Để Chạy Tool Reg Pro5", "obf-reg_pro5.py"),
    "4.2": ("Để Chạy Tool Tăng Cảm Xúc Pro5", "obf-tangcx_pro5.py"),
    "4.3": ("Để Chạy Tool Tăng Follow Pro5", "obf-tangfollow_pro5.py"),
    "4.4": ("Để Chạy Tool Tăng View Story Pro5", "obf-tangviewstory_pro5.py"),
    "4.5": ("Để Chạy Tool Tăng Comment Pro5", "obf-tangcomment_pro5.py"),
    "4.6": ("Để Chạy Tool Tăng Like Page Pro5", "obf-tanglikepage_pro5.py"),
    "4.7": ("Để Chạy Tool Tăng Mem Group Pro5", "obf-tangmemgroup_pro5.py"),
    "4.8": ("Để Chạy Tool Spam Messenger", "obf-messenger.py"),
}
