tool_map = {
    "1.1": ("Để Chạy Tool Golike Instagram", "obf-golike_instagram.py"),
    "1.2": ("Để Chạy Tool Golike Threads", "obf-golike_threads.py"),
    "1.3": ("Để Chạy Tool Golike Pinterest", "obf-golike_pinterest.py"),
    "1.4": ("Để Chạy Tool Golike Twitter", "obf-golike_twitter.py"),
    "1.5": ("Để Chạy Tool Golike Linkedin", "obf-golike_linkedin.py"),
    "1.6": ("Để Chạy Tool Golike Facebook \033[1;31mv1 \033[1;36m(ADB + Cookie)", "obf-golike_fb.py"),
    "1.7": ("Để Chạy Tool Golike Facebook \033[1;31mv2 \033[1;36m(ADB + Đa Cookie)", "obf-golike_fb2.py"),
    "1.8": ("Để Chạy Tool Golike Snapchat \033[1;36m(Auto Click)", "obf-golike_snapchat.py"),
    "1.9": ("Để Chạy Tool Golike Tiktok \033[1;36m(Auto Click)", "obf-golike_tiktok.py"),
    "2.1": ("Để Chạy Tool TDS Facebook", "obf-tds_facebook.py"),
    "2.2": ("Để Chạy Tool TDS Pro5", "obf-tds_pro5.py"),
    "2.3": ("Để Chạy Tool TDS Instagram", "obf-tds_instagram.py"),
    "2.4": ("Để Chạy Tool TDS TikTok \033[1;36m(Auto Click)", "obf-tds_tiktok.py"),
    "3.1": ("Để Chạy Tool TTC Facebook", "obf-ttc_facebook.py"),
    "3.2": ("Để Chạy Tool TTC Pro5", "obf-ttc_pro5.py"),
    "3.3": ("Để Chạy Tool TTC Instagram \033[1;36m(VIPIG)", "obf-ttc_instagram.py"),
    "3.4": ("Để Chạy Tool TTC Threads \033[1;36m(VIPIG)", "obf-ttc_threads.py"),
    "3.5": ("Để Chạy Tool TTC TikTok \033[1;36m(Auto Click)", "obf-ttc_tiktok.py"),
    "4.1": ("Để Chạy Tool Reg Pro5", "obf-reg_pro5.py"),
    "4.2": ("Để Chạy Tool Tăng Tương Tác Bằng Pro5 \033[1;36m(7 chế độ)", "obf-buffpro5.py"),
    "4.3": ("Để Chạy Tool Spam Messenger", "obf-messenger.py"),
    "4.4": ("Để Chạy Tool Nuôi Facebook \033[1;36m(Thả Cảm Xúc, Bình Luận, Theo Dõi, Chia Sẻ, Like Page, Tham Gia Group, Thêm Bạn Bè)", "obf-nuoiacc.py"),
    "5.1": ("Để Chạy Tool Xworld Vua Thoát Hiểm", "obf-xw_vth.py"),
}
