tool_map = {
    "1.1": ("Để Chạy Tool Golike Instagram", "obf-golike_instagram.py"),
    "1.2": ("Để Chạy Tool Golike Threads", "obf-golike_threads.py"),
    "1.3": ("Để Chạy Tool Golike Tiktok", "obf-golike_tiktok.py"),
    "2.1": ("Để Chạy Tool TDS Facebook", "obf-tds_facebook.py"),
    "2.2": ("Để Chạy Tool TDS Pro5", "obf-tds_pro5.py"),
    "2.3": ("Để Chạy Tool TDS Instagram", "obf-tds_instagram.py"),
    "2.4": ("Để Chạy Tool TDS TikTok", "obf-tds_tiktok.py"),
    "3.1": ("Để Chạy Tool TTC Facebook", "obf-ttc_facebook.py"),
    "3.2": ("Để Chạy Tool TTC Pro5", "obf-ttc_pro5.py"),
    "3.3": ("Để Chạy Tool TTC Instagram \033[1;31mBảo trì", "obf-ttc_instagram.py"),
    "3.4": ("Để Chạy Tool TTC TikTok", "obf-ttc_tiktok.py"),
    "4.1": ("Để Chạy Tool Reg Pro5", "obf-reg_pro5.py"),
    "4.2": ("Để Chạy Tool Tăng Tương Tác Bằng Pro5 \033[1;36m(7 chế độ)", "obf-buffpro5.py"),
    "4.3": ("Để Chạy Tool Kết Bạn Gợi Ý", "obf-addfb.py"),
    "4.4": ("Để Chạy Tool Spam Messenger", "obf-messenger.py"),
    "4.5": ("Để Chạy Tool Get Cookie & Token", "obf-getcookie.py"),
    "4.6": ("Để Chạy Tool Nuôi Facebook", "obf-nuoiacc.py"),
    "5.1": ("Để Chạy Tool Tăng Tương Tác Tiktok", "obf-tiktok.py"),
}
